sudo: required
language: python
python:
    - "2.7"
env:
    - PYTHONPATH=/home/travis/heat:/home/travis/f5-common-python:$PWD
before_install:
    - sudo apt-get -qq update
    - git config --global user.email "OpenStack_TravisCI@f5.com"
    - git config --global user.name "Travis F5 Openstack"
    - git fetch --depth=100
    - sudo apt-get -y install build-essential libssl-dev libffi-dev python-dev
    - git clone -b stable/kilo https://github.com/openstack/heat.git ~/heat
install:
    - pip install -r requirements.test.txt
    - pip install -r ~/heat/requirements.txt
script:
    - flake8 f5_heat/resources/
    - py.test f5_heat/resources/test --cov=f5_heat/resources
    - python setup.py sdist
    - cd docs
    - make html
    - cd ../
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  server: https://pypi.python.org/pypi
  on:
     all_branches: true
     tags: true
     python: 2.7
  skip_cleanup: true
notifications:
    slack:
      rooms:
        - $SLACK_TOKEN
        - $SLACK_TOKEN
      on_success: change
      on_failure: always
