sudo: required
language: python
python:
    - "2.7"
env:
    - PYTHONPATH=~/heat:/home/travis/f5-common-python:$PWD
before_install:
    - sudo apt-get -qq update
    - git config --global user.email "OpenStack_TravisCI@f5.com"
    - git config --global user.name "Travis F5 Openstack"
    - sudo apt-get -y install build-essential libssl-dev libffi-dev python-dev
    - git clone https://github.com/openstack/heat.git ~/heat
    - cd ~/heat/
    - git checkout tags/kilo-eol
    - cd $TRAVIS_BUILD_DIR
install:
    - pip install -r requirements.unit.test.txt
    - pip install -r ~/heat/requirements.txt
    - pip install -r requirements.docs.txt
script:
    - flake8 f5_heat/resources/
    - py.test f5_heat/resources/test --cov=f5_heat/resources
    - python setup.py sdist
    - cd docs
    - make html
    - cd ../
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  server: https://pypi.python.org/pypi
  on:
     all_branches: true
     tags: true
     python: 2.7
  skip_cleanup: true
notifications:
    slack:
      rooms:
        - secure: kjJ6LIczHtuVvlxv4DdDMbM9RyiJU+YOLDWooHezooj/t8UbACwHUmrXAdybRXqxXykTbW/aCcWuY4hX7i4gbaX1m3CUG4wnFMkISSyQdEMQUB5pWr3wUDxFMuBGhkFfo9g/sNOSfpMJ0i5g3hkg1Ig8N/TeFRKONcAd7yXS5hrMy8W3ApmAdmeTtvKJsXWC1EnM9Z2l5mBQyx0Dpe2/Xoe3uqySYRnJm2z2upmtML8uY+OKxZ1wWI/8bCjtzEIpsHJilMSMhoudHRhCGcRXp8FXnYxQ1FuRxVxnwvShGWa68vaDB7WCt6xjFMzgm4d53tAASb8hhr5/HhzOwOTQIGo2ahEdLMDZ+Po75y6N55RFr8Xl3h4d98QZBfBR91BLmPg04HJJUdZG4BjjStVvXvmX0X91CW1XTUtmVrO0ohj3L6Nw1ohMv0PLGufRxLJlZ5vsgGEVC+QjY/88cK8LKG2iVkAg9PJ2QanDU7UvTCTS/SrJZoT6UP6W+XZPuhoIPmjO1MqEaibWvqByegA7MsNbi0KLhRajqKUQuNpfOxvchEv70SRFhn9KQCspGn1HbmAGjV17gVwduBw1lZWcoLtAKMwwNdusswfiu/fZsdHgxssN0aR2eFjN/KWnYvphmkPbL8UOitUbMehGEjz2V/tnQGm14NnxC+uWzwyaCCM=
        - secure: SUKOH8gDCnSCO969XPttA9bxTI6BACqTJgCLl6MDY1siRhTOyVmww1g989Pg9uKc1Hy+IKGDFdy0/+SXURCbj9xMEVOCGGhdM6Jo2xa/6yjTsS1X4auxegBaGEdSWVD7zUz8qKc/uc3Z0L3K5AHG4zHyJQeFsCcxouMktwCsreYap88H7weCQItEXxb9aRFOMZHeRsaJ8RLfhmF3hHHgQtase4JMbXM8uAm9tgOH9cCq0+W3/eaAGFFgzKH1D7GoWG5a94kNHFRgrFP6V560r6chxu7m3CL4EiPuAfExAQz3nlb7sCgWzWqNqsa9GbCi6GiAXS0OnQ10BPY/4oPWdWvi4EeX1RWeEfZmazo2XvSoVIdG6JHawH4DhHeReWY/hy0wLNGjeUxX29kJ6OLWvSm3zw+j1Gjs5TWqS85Aa3DY4bbb0kWfyW2EjmPTuZc91FUIYPM8W4DnXF+qqB46dbTZfE0aHJ/2sEz12ZaJxO4Uvym70/yYW77rfBBHg7o1ZCqTEFQXIx0+sxhHwbEZBtXt0lmPLR2vs45Yn5b3mX9i3gob8PVJ/ytE9UR+cjKWM665J2PhWo0rkW+J7+s4CZCJwQ8Noi6Rj8Ex3ImXvpdyB2UiYP5xMPDbzbPt6yO3GperXkMwjk+dixH+LA2f1Z2FlRC2oGAeue2oo3ou9X8=
      on_success: change
      on_failure: always
